# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=None, null=True, upload_to='media/sample_img/'),
        ),
    ]
