# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180728_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='media/sample_img/'),
            preserve_default=False,
        ),
    ]
