# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookcatg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buk_cover', models.ImageField(blank=True, null=True, upload_to='sample_img/')),
                ('buk_name', models.CharField(max_length=100)),
                ('buk_author', models.CharField(max_length=200)),
                ('buk_price', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=15)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('buk_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('catg_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buk.Bookcatg')),
            ],
        ),
    ]
