# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buk', '0003_auto_20180811_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='buk_author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='buk_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='buk_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='catg_type',
            field=models.CharField(blank=True, choices=[('COMEDY', 'COMEDY'), ('HORROR', 'HORROR'), ('ROMANCE', 'ROMANCE'), ('KIDS', 'KIDS'), ('SCIENCE', 'SCIENCE'), ('LITERATURE', 'LITERATURE'), ('FAIRY TALES', 'FAIRY TALES'), ('MYSTERY', 'MYSTERY'), ('DRAMA', 'DRAMA'), ('COOKING', 'COOKING')], max_length=100, null=True),
        ),
    ]
